In [4]:
import numpy as np

In [3]:
L = [1,2,3]

In [4]:
A = np.array([1,2,3])

In [5]:
for e in L:
  print(e)

1
2
3


In [6]:
for e in A:
  print(e)

1
2
3


In [7]:
L.append(4)
L

[1, 2, 3, 4]

In [8]:
A.append(4)

AttributeError: ignored

In [9]:
L + [5]

[1, 2, 3, 4, 5]

In [10]:
A + np.array([4])

array([5, 6, 7])

In [11]:
A + np.array([4,5,6])

array([5, 7, 9])

In [12]:
A + np.array([4,5])

ValueError: ignored

In [13]:
2 * A

array([2, 4, 6])

In [14]:
2*L


[1, 2, 3, 4, 1, 2, 3, 4]

In [15]:
L+L


[1, 2, 3, 4, 1, 2, 3, 4]

In [16]:
L2 = []

for i in L:
  L2.append(i + 3)

In [17]:
L2

[4, 5, 6, 7]

In [18]:
L2 = [e + 3 for e in L]

In [19]:
L2

[4, 5, 6, 7]

In [20]:
L**2


TypeError: ignored

In [21]:
L2=[]

for e in L:
  L2.append(e**2)

In [22]:
L2

[1, 4, 9, 16]

In [23]:
A**2

array([1, 4, 9])

In [24]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [25]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [26]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [27]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

In [29]:
a = np.array([1,2])
b = np.array([3,4])

In [30]:
dot = 0
for e,f in zip(a,b):
  dot += e*f
dot

11

In [32]:
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [33]:
a*b

array([3, 8])

In [35]:
np.sum(a*b)

11

In [36]:
np.dot(a,b)

11

In [37]:
a.dot(b)

11

In [39]:
a @ b #same as n.dot

11

In [41]:
amag = np.sqrt(np.sum(a*a))
amag

2.23606797749979

In [42]:
np.linalg.norm(a)

2.23606797749979

In [43]:
cosangle = a.dot(b) / (np.linalg.norm(a)*np.linalg.norm(b))
cosangle


0.9838699100999074

In [45]:
angle = np.arccos(cosangle)
angle

0.17985349979247847

In [48]:
## speed comparison ##
import numpy as np
from datetime import datetime

# note: you can also use %timeit

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
  result = 0
  for e, f in zip(a, b):
    result += e*f
  return result

t0 = datetime.now()
for t in range(T):
  slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds())

dt1 / dt2: 69.81100338565713


In [49]:
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [50]:
L[0]

[1, 2]

In [51]:
L[0][1]

2

In [52]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [53]:
A[0][1]

2

In [54]:
A[0,1]

2

In [57]:
A[:,1]

array([2, 4])

In [58]:
A.T

array([[1, 3],
       [2, 4]])

In [59]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [60]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [61]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
np.dot(A,B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [63]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [64]:
np.dot(A,B.T)

ValueError: ignored

In [65]:
np.linalg.det(A)

-2.0000000000000004

In [66]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [70]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [71]:
np.trace(A)

5

In [72]:
np.diag(A)

array([1, 4])

In [73]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [74]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [75]:
Lam, V = np.linalg.eig(A)

In [80]:
V[:,0]* Lam[0] == A @ V[:,0]

array([ True, False])

In [83]:
V[:,0]* Lam[0] , A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [84]:
np.allclose(V[:,0]* Lam[0] , A @ V[:,0])

True

In [86]:
np.allclose(V @ np.diag(Lam), A@V)

True

In [5]:
A = np.array([[1,1],[1.5,4]])
B = np.array([2200,5050])

In [6]:
np.linalg.solve(A, B)

array([1500.,  700.])

In [8]:
np.linalg.inv(A).dot(B)

array([1500.,  700.])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.ones((2,3))*10

array([[10., 10., 10.],
       [10., 10., 10.]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.random.random((2,4)) # numbers from 0 and 1

array([[0.5475117 , 0.70271409, 0.6056608 , 0.88230569],
       [0.46051791, 0.56206241, 0.80752713, 0.7516555 ]])

In [18]:
np.random.randn(2,3) # standard distribution gaussian distribution

array([[-1.03410332,  1.12176858,  0.16920957],
       [ 0.00273058, -0.30139331,  1.07388525]])

In [19]:
R = np.random.randn(1000)

In [20]:
R.mean()

0.00973361322645979

In [21]:
np.mean(R)

0.00973361322645979

In [23]:
R.var() #varience

0.9612692548828273

In [25]:
R.std() #squar root of varience

0.9804433970825788

In [26]:
R = np.random.randn(10000, 3)

In [27]:
R.mean(axis = 0)

array([-0.00478371,  0.00808361, -0.0038736 ])

In [29]:
R.mean(axis = 1).shape

(10000,)

In [30]:
np.cov(R) #covarience

array([[ 0.19358513, -0.29038738,  0.08378017, ..., -0.37285525,
        -0.04616167, -0.39602629],
       [-0.29038738,  0.88378846, -0.75161804, ...,  0.99191553,
         0.07723818,  0.45154608],
       [ 0.08378017, -0.75161804,  0.91044778, ..., -0.76555129,
        -0.03114142,  0.02763999],
       ...,
       [-0.37285525,  0.99191553, -0.76555129, ...,  1.13571568,
         0.09662535,  0.62520819],
       [-0.04616167,  0.07723818, -0.03114142, ...,  0.09662535,
         0.01115012,  0.09189346],
       [-0.39602629,  0.45154608,  0.02763999, ...,  0.62520819,
         0.09189346,  0.85548512]])

In [31]:
np.cov(R).shape #cov function by default treats each column as a vector observation

(10000, 10000)

In [32]:
np.cov(R.T) #fixing vector observation

array([[ 1.02174588, -0.00384602, -0.01461062],
       [-0.00384602,  0.98002357, -0.00426611],
       [-0.01461062, -0.00426611,  0.97568162]])

In [33]:
np.cov(R, rowvar=False) #another way to fix vector observation

array([[ 1.02174588, -0.00384602, -0.01461062],
       [-0.00384602,  0.98002357, -0.00426611],
       [-0.01461062, -0.00426611,  0.97568162]])

In [34]:
np.random.randint(0,10,size = (3,3))

array([[7, 9, 2],
       [2, 2, 9],
       [7, 7, 0]])

In [42]:
np.random.choice(10, size = (3,3))

array([[1, 8, 0],
       [9, 6, 2],
       [5, 1, 8]])